<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUy4tph6\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUy4tph6/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUy4tph6.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUy4tph6\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUy4tph6\appProdProjectContainer(array(
    'container.build_hash' => 'Uy4tph6',
    'container.build_id' => '5f51db29',
    'container.build_time' => 1543755417,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerUy4tph6');
