<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJv8xzq3\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJv8xzq3/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerJv8xzq3.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerJv8xzq3\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerJv8xzq3\appProdProjectContainer(array(
    'container.build_hash' => 'Jv8xzq3',
    'container.build_id' => '77ee2794',
    'container.build_time' => 1544439362,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJv8xzq3');
